### ISSUE TITLE
No Full code

### ISSUE THREAD

**Issue by BayLee001** [DevinJake/NS-CQA#1]
![image](https://user-images.githubusercontent.com/27198552/97008611-a3e54280-1575-11eb-93f5-fcc9d5fdb4f0.png)

**Comment by DevinJake** [comment]
We will release the code soon when we finished cleaning it.
At that time, we will inform you.
Cheers!

**Comment by DevinJake** [comment]
We will release the code soon when we finished cleaning it.
We have too many new processed materials waiting for uploading onto Google drive, that will take some time.
When everything is done, we will inform you.
Cheers!

**Comment by DevinJake** [comment]
Dear all:
We have added READ.ME and explained everything that is required to reproduce the results.
Please be informed, cheers!
