### ISSUE TITLE
Pretraining process and experiment on Webquestions SP

### ISSUE THREAD

**Issue by Snnzhao** [DevinJake/NS-CQA#27]
I am interested with your pretraining process but I can not find the code for it.
Could you please provide the code for it?
Since CSQA is a very big dataset, running your work on it take a lot of time.
It will help a lot  if you can provide the work on Webquestions SP

**Comment by DevinJake** [comment]
Hi, Snnzhao.
Don't worry, the training time of webquestionssp is much less than CSQA, which cost several hours to finish training.
We are working on cleaning the code and will upload the code together with the dataset very soon.

As to pre-training, we employed a teacher-forcing paradigm to train the model and will provide the code once we finish cleaning the code.

**Comment by Snnzhao** [comment]
Thanks for that.
And thanks again for providing such outstanding work

**Comment by DevinJake** [comment]
> I am interested with your pretraining process but I can not find the code for it.
> Could you please provide the code for it?
> Since CSQA is a very big dataset, running your work on it take a lot of time.
> It will help a lot if you can provide the work on Webquestions SP

Hi, Snnzhao:

We have uploaded the source code 'train_crossent.py' and the corresponding dataset for pre-training.
You could check them for details.

If you want to pre-train the models by yourself, you could:
1. Download the 'PT_train_INT.question' and 'PT_train_INT.action' from the data link https://drive.google.com/drive/folders/1J8C2AQ1PmzBWKKmgeSMRSWgMTVjJbbbI. Put them under the folder 'data\auto_QA_data\mask_even_1.0%'. The files are the pseudo-gold annotations that were formed by using the BFS algorithm.
2. Run python file 'S2SRL\train_crossent.py'.
3. Under the folder 'data\saves\pretrained' you could find the models, which are trained under the teacher-forcing paradigm. The models are named following the format 'pre_bleu_TestingScore_numberOfEpochs.dat'. Normally we chose the model with the highest bleu testing score as the pre-trained model for following RL training. Or you could choose whatever model you like. 
4. The performance of the chosen model might have a tiny difference between the uploaded pre-trained model 'pre_bleu_0.956_43.dat'. We recommend you to choose 'pre_bleu_0.956_43.dat' for re-implementation.

We also update the README to explain how to conduct pre-training.
Cheers!

**Comment by Snnzhao** [comment]
Hi, DevinJake.
Thanks for your newly updated code for pretraining, that helps a lot.

**Comment by Snnzhao** [comment]
Also, looking forward to your experiment on WebquestionSP.  
Thanks again for providing such outstanding work.

**Comment by Snnzhao** [comment]
I' m also working on reimplementing the work of NSM on WebquestionSP.
Never want to bother you, but it will help a lot if you can provide me with your implement of the baseline.
Best wishes.

**Comment by Snnzhao** [comment]
> The files are the pseudo-gold annotations that were formed by using the BFS algorithm.

Hi, DevinJake.
Could you also provide the code for generating the pseudo-gold annotations?
I am also interested in this part of your talent work.

**Comment by DevinJake** [comment]
> Also, looking forward to your experiment on WebquestionSP.
> Thanks again for providing such outstanding work.

Hi, Snnzhao,
We have uploaded the codes and the materials related to the webquestionssp dataset and updated the README as well.
Please refer to them to try to re-implement the models under the webquestionssp dataset.
Cheers!
