### ISSUE TITLE
The meaning of WithINT

### ISSUE THREAD

**Issue by Snnzhao** [DevinJake/NS-CQA#28]
I find the some provided datasets have INT at end while some are not.
CSQA_ANNOTATIONS_test.json and CSQA_ANNOTATIONS_test_INT.json for example
What is the difference between these two datasets

**Comment by DevinJake** [comment]
Hi, Snnzhao.
We found some issues before and we have solved the problem.
Suppose we were answering the question 'How many countries have the rivers more than 100', if we used the files without 'INT' to train the model, the model would not output '100' in the action sequence at all.
That is a serious problem, isn't that?
Luckily, we have solved the problem, and name the file with 'INT' at the end.
That's our problem that we still uploaded the original files onto the Google drive.
Please use the file with INT to train the model.
Cheers!
