### ISSUE TITLE
Trouble when reimplement baseline CIPITR

### ISSUE THREAD

**Issue by Snnzhao** [DevinJake/NS-CQA#42]
When reimplement baseline CIPITR on webqeustionSP, if setting the question type all, the outer index error for GPU occur:
/pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [7,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

Have you ever meet this problem?
Could you please help me out with it?

**Comment by DevinJake** [comment]
Sorry, we did not face this problem.
My labmate said that it might be about the python version.
Cheers!

**Comment by DevinJake** [comment]
> When reimplement baseline CIPITR on webqeustionSP, if setting the question type all, the outer index error for GPU occur:
> /pytorch/aten/src/THC/THCTensorIndex.cu:361: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2, IndexIsMajor = true]: block: [7,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
> 
> Have you ever meet this problem?
> Could you please help me out with it?

Sorry, we did not face this problem.
My labmate said that it might be about the PyTorch version problem.
Cheers!
